export { AiService } from './lib/ai.service';
export type { ChatMessage } from './lib/ide-store/ai-chat.store';
export { AuthService } from './lib/auth.service';
export { WorkspaceService } from './lib/workspace.service';
export { FileExplorerService } from './lib/file-explorer.service';
export { GitService } from './lib/git.service';
export { TerminalWsService } from './lib/terminal-ws.service';
export { GitStatusStore } from './lib/ide-store';
export { VoiceService } from './lib/voice.service';
export { withGitActions } from './lib/partial-store/with-git-actions.store';
export * as IdeStore from './lib/ide-store';
