import { VoiceControl } from '@org/shared/contracts';

export interface VoiceCommandDescriptor {
  intent: VoiceControl.VoiceIntent;
  label: string;
  category: 'git' | 'editor' | 'layout' | 'ai' | 'terminal' | 'file' | 'tool';
  requiredParams: string[];
  voiceExample: string;
}

export const VOICE_COMMANDS: VoiceCommandDescriptor[] = [
  {
    intent: VoiceControl.VoiceIntent.GitCommit,
    label: 'Commit',
    category: 'git',
    requiredParams: ['message'],
    voiceExample: '"commit with message fix login bug"',
  },
  {
    intent: VoiceControl.VoiceIntent.GitPush,
    label: 'Push',
    category: 'git',
    requiredParams: [],
    voiceExample: '"push to remote"',
  },
  {
    intent: VoiceControl.VoiceIntent.GitStageAll,
    label: 'Stage All',
    category: 'git',
    requiredParams: [],
    voiceExample: '"stage all changes"',
  },
  {
    intent: VoiceControl.VoiceIntent.GitStash,
    label: 'Stash',
    category: 'git',
    requiredParams: [],
    voiceExample: '"stash my changes"',
  },
  {
    intent: VoiceControl.VoiceIntent.EditorSave,
    label: 'Save File',
    category: 'editor',
    requiredParams: [],
    voiceExample: '"save the file"',
  },
  {
    intent: VoiceControl.VoiceIntent.EditorCloseTab,
    label: 'Close Tab',
    category: 'editor',
    requiredParams: [],
    voiceExample: '"close this tab"',
  },
  {
    intent: VoiceControl.VoiceIntent.LayoutToggleTerminal,
    label: 'Toggle Terminal',
    category: 'layout',
    requiredParams: [],
    voiceExample: '"open terminal"',
  },
  {
    intent: VoiceControl.VoiceIntent.LayoutSwitchPanel,
    label: 'Switch Panel',
    category: 'layout',
    requiredParams: ['panel'],
    voiceExample: '"switch to git panel"',
  },
  {
    intent: VoiceControl.VoiceIntent.AiChat,
    label: 'AI Chat',
    category: 'ai',
    requiredParams: ['message'],
    voiceExample: '"ask AI how to implement sorting"',
  },
  {
    intent: VoiceControl.VoiceIntent.AiExplain,
    label: 'Explain File',
    category: 'ai',
    requiredParams: [],
    voiceExample: '"explain this file"',
  },
  {
    intent: VoiceControl.VoiceIntent.TerminalRun,
    label: 'Run Command',
    category: 'terminal',
    requiredParams: ['command'],
    voiceExample: '"run npm install"',
  },
  {
    intent: VoiceControl.VoiceIntent.FileCreate,
    label: 'Create File',
    category: 'file',
    requiredParams: ['path'],
    voiceExample: '"create file utils.ts"',
  },
  {
    intent: VoiceControl.VoiceIntent.DirCreate,
    label: 'Create Directory',
    category: 'file',
    requiredParams: ['path'],
    voiceExample: '"create directory src/helpers"',
  },
  {
    intent: VoiceControl.VoiceIntent.TerminalClear,
    label: 'Clear Terminal',
    category: 'terminal',
    requiredParams: [],
    voiceExample: '"clear the terminal"',
  },
  {
    intent: VoiceControl.VoiceIntent.TerminalNewSession,
    label: 'New Terminal',
    category: 'terminal',
    requiredParams: [],
    voiceExample: '"open new terminal"',
  },
  {
    intent: VoiceControl.VoiceIntent.TerminalKill,
    label: 'Kill Process',
    category: 'terminal',
    requiredParams: [],
    voiceExample: '"stop the terminal"',
  },
  {
    intent: VoiceControl.VoiceIntent.AiReview,
    label: 'Review Code',
    category: 'ai',
    requiredParams: [],
    voiceExample: '"review this code"',
  },
  {
    intent: VoiceControl.VoiceIntent.AiRefactor,
    label: 'Refactor Code',
    category: 'ai',
    requiredParams: [],
    voiceExample: '"refactor to use async await"',
  },
  {
    intent: VoiceControl.VoiceIntent.AiFixError,
    label: 'Fix Error',
    category: 'ai',
    requiredParams: [],
    voiceExample: '"fix the null pointer error"',
  },
  {
    intent: VoiceControl.VoiceIntent.GitStashPop,
    label: 'Pop Stash',
    category: 'git',
    requiredParams: [],
    voiceExample: '"pop stash"',
  },
  {
    intent: VoiceControl.VoiceIntent.GitUnstageAll,
    label: 'Unstage All',
    category: 'git',
    requiredParams: [],
    voiceExample: '"unstage all"',
  },
  {
    intent: VoiceControl.VoiceIntent.GitDiscardAll,
    label: 'Discard Changes',
    category: 'git',
    requiredParams: [],
    voiceExample: '"discard all changes"',
  },
  {
    intent: VoiceControl.VoiceIntent.GitCheckout,
    label: 'Checkout Branch',
    category: 'git',
    requiredParams: ['branch'],
    voiceExample: '"checkout main"',
  },
  {
    intent: VoiceControl.VoiceIntent.EditorCloseAll,
    label: 'Close All Tabs',
    category: 'editor',
    requiredParams: [],
    voiceExample: '"close all tabs"',
  },
  {
    intent: VoiceControl.VoiceIntent.EditorCloseOthers,
    label: 'Close Other Tabs',
    category: 'editor',
    requiredParams: [],
    voiceExample: '"close other tabs"',
  },
  {
    intent: VoiceControl.VoiceIntent.LayoutToggleSidebar,
    label: 'Toggle Sidebar',
    category: 'layout',
    requiredParams: [],
    voiceExample: '"toggle sidebar"',
  },
  {
    intent: VoiceControl.VoiceIntent.AiClearChat,
    label: 'Clear Chat',
    category: 'ai',
    requiredParams: [],
    voiceExample: '"clear chat"',
  },
  {
    intent: VoiceControl.VoiceIntent.AiPlan,
    label: 'Plan Feature',
    category: 'ai',
    requiredParams: ['message'],
    voiceExample: '"plan the authentication feature"',
  },
  {
    intent: VoiceControl.VoiceIntent.AiDocument,
    label: 'Document File',
    category: 'ai',
    requiredParams: [],
    voiceExample: '"document this file"',
  },
  {
    intent: VoiceControl.VoiceIntent.AiTicket,
    label: 'Create Ticket',
    category: 'ai',
    requiredParams: ['message'],
    voiceExample: '"create a ticket for the login bug"',
  },
  {
    intent: VoiceControl.VoiceIntent.AiChain,
    label: 'Chain Commands',
    category: 'ai',
    requiredParams: ['message'],
    voiceExample: '"review this code and suggest a commit message"',
  },
  {
    intent: VoiceControl.VoiceIntent.ToolInstallClaude,
    label: 'Install Claude Code',
    category: 'tool',
    requiredParams: [],
    voiceExample: '"install claude"',
  },
  {
    intent: VoiceControl.VoiceIntent.ToolRunClaude,
    label: 'Run Claude Code',
    category: 'tool',
    requiredParams: [],
    voiceExample: '"use claude" or "open claude"',
  },
];
