export enum FileType {
  TS = 'ts',
  JS = 'js',
  HTML = 'html',
  CSS = 'css',
  SCSS = 'scss',
  JSON = 'json',
  MD = 'md',
  TXT = 'txt',
  PNG = 'png',
  JPG = 'jpg',
  SVG = 'svg',
  PDF = 'pdf',
  OTHER = 'other',
  DIRECTORY = 'directory',
}
