export enum EnvironmentVariables {
  PORT = 'PORT',
  CORS_ORIGINS = 'CORS_ORIGINS',
  REDIS_URL = 'REDIS_URL',
  OAUTH_CLIENT_ID = 'OAUTH_CLIENT_ID',
  OAUTH_CLIENT_SECRET = 'OAUTH_CLIENT_SECRET',
  OAUTH_CALLBACK_URL = 'OAUTH_CALLBACK_URL',
  FRONTEND_URL = 'FRONTEND_URL',
  WORKSPACE_BASE_DIR = 'WORKSPACE_BASE_DIR',
  DEMO_REPO_URL = 'DEMO_REPO_URL',
  DEMO_WORKSPACE_PATH = 'DEMO_WORKSPACE_PATH',
  NODE_ENV = 'NODE_ENV',
}
