name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    uses: ./.github/workflows/deploy-shared.yml
    with:
      branch: dev
      angular-base-href: /angular/
      vite-base: /react/
      angular-upload-path: /var/www/kod3.dev/angular/
      react-upload-path: /var/www/kod3.dev/react/
      deploy-dir: /opt/kode
      compose-file: docker-compose.yml
      env-file: .env.production
      angular-configuration: production
    secrets: inherit
